spring.application.name=service
server.port=4001

#swagger >>>>

springdoc.api-docs.enable=true
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json
